function init_figure(popts)
% INIT_FIGURE  Initialize figure.

  error(nargchk(0, 1, nargin))     
  if nargin == 0
    popts = [];
  end
  
  fheight   = PARS('figure_height', popts);
  fwidth    = PARS('figure_width', popts);
  
  % set properties of plots
  clf
  set(gcf, 'Units', 'inches', 'PaperUnits', 'inches')
  psize     = get(gcf, 'PaperSize');
  fpos      = get(gcf, 'Position');

  ppos      = [(psize(1) - fwidth)/2, (psize(2) - fheight)/2, fwidth, fheight];
  fpos      = [fpos(1) fpos(2) fpos(3) fpos(3)*fheight/fwidth];
  set(gcf, 'PaperPosition', ppos, ...
	   'Position', fpos, ...
	   'DefaultLineLineWidth', PARS('line_width', popts), ...
	   'DefaultLineMarkerSize', PARS('marker_size', popts), ...
	   'DefaultAxesFontSize',  PARS('font_size', popts), ...
	   'DefaultTextInterpreter', 'tex', ...
	   'DefaultTextFontSize',  PARS('font_size', popts), ...
	   'DefaultTextFontName', 'Helvetica', ...
	   'DefaultAxesFontName', 'Helvetica', ...
	   'DefaultAxesLayer', 'top', ...
	   'DefaultAxesTickDir', 'out', ...
	   'DefaultAxesXMinorTick', 'off', ...
	   'DefaultAxesYMinorTick', 'off', ...
	   'DefaultAxesLineWidth', PARS('axes_line_width', popts), ...
	   'DefaultAxesTickLength', PARS('tick_length', popts), ...
           'DefaultAxesPosition', [.16  .2 .8 .8] );
          % 'DefaultAxesPosition', [.15 .18 .85 .815] ) % wv review
%	   'DefaultAxesPosition', [.135 .17 .85 .815]);




